#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinAndroid.Resource", IsApplication=true)]

namespace XamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int time = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int Backtext_H = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int Backtext_Interval_M = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int Backtext_Interval_S = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int Backtext_M = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int Backtext_S = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int MyText = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int TimeSUMText = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int button_Cancel = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button_Start = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int spinner_H = 2131099654;
			
			// aapt resource value: 0x7f060017
			public const int spinner_Interval_M = 2131099671;
			
			// aapt resource value: 0x7f060014
			public const int spinner_Interval_S = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int spinner_M = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int spinner_S = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int textView10 = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int textView11 = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int textView12 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int textView13 = 2131099673;
			
			// aapt resource value: 0x7f060007
			public const int textView6 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView7 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int textView8 = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int text_H = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int text_M = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int text_S = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
