#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinAndroid.Resource", IsApplication=true)]

namespace XamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int time = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int Backtext_H = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int Backtext_Interval_M = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int Backtext_Interval_S = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int Backtext_M = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Backtext_S = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int MyText = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int button_Cancel = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int button_Start = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int spinner_H = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int spinner_Interval_M = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int spinner_Interval_S = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int spinner_M = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int spinner_S = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textView10 = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int textView11 = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int textView12 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int textView13 = 2131165208;
			
			// aapt resource value: 0x7f070007
			public const int textView6 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int textView7 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textView8 = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int text_H = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int text_M = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int text_S = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int alerm = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int test = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
